services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spa-pure-js
    ports:
      - "8080:80"
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    develop:
      watch:
        - action: sync
          path: ./src
          target: /usr/share/nginx/html
          ignore:
            - node_modules/
        - action: rebuild
          path: ./nginx.conf
        - action: rebuild
          path: ./Dockerfile